spring:
  application:
    name: customer-service


  datasource:
    url: jdbc:mysql://localhost:3306/customer_master?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: False

       
